name: Exemplo

on: [push]

jobs:
  Inicial:
    runs-on: ubuntu-latest
    steps:
      - name: Título da Tarefa
        run: echo "Executando ma VM do git"

      - name: Segunda Tarefa
        run: pwd

      - name: Terceiro Tarefa
        run: whoami

